# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Eloypinol.github.io/rapid/"

git_url = "https://github.com/Eloypinol/rapid/tree/master/"

def custom_doc_links(name): return None
